name: CI/CD Build → Push

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  REGISTRY: ${{ secrets.REGISTRY }}
  IMAGE_NAME: ${{ secrets.IMAGE_NAME }}
  K8S_NAMESPACE: ${{ secrets.K8S_NAMESPACE || 'default' }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    outputs:
      image_full: ${{ steps.set-image.outputs.image_full }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME || secrets.GHCR_USERNAME || github.actor }}
          password: ${{ secrets.DOCKER_PASSWORD || secrets.GHCR_TOKEN || secrets.GITHUB_TOKEN }}

      - name: Build and push image
        id: build
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: maddalagayathri/flask-hello:${{ github.sha }}
          file: ./Dockerfile

      - name: Set image variable
        id: set-image
        run: |
          echo "image_full=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}" >> $GITHUB_OUTPUT

      - name: Display image info
        run: |
          echo "Docker image built and pushed successfully!"
          echo "Image: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}"
          echo "Deploy manually using: kubectl set image deployment/myapp myapp=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}"
