name: CI/CD Build → Push → Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  REGISTRY: ${{ secrets.REGISTRY }}
  IMAGE_NAME: ${{ secrets.IMAGE_NAME }}
  K8S_NAMESPACE: ${{ secrets.K8S_NAMESPACE || 'default' }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    outputs:
      image_full: ${{ steps.set-image.outputs.image_full }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME || secrets.GHCR_USERNAME || github.actor }}
          password: ${{ secrets.DOCKER_PASSWORD || secrets.GHCR_TOKEN || secrets.GITHUB_TOKEN }}

      - name: Build and push image
        id: build
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: maddalagayathri/flask-hello:${{ github.sha }}
          file: ./Dockerfile

      - name: Set image variable
        id: set-image
        run: |
          echo "image_full=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}" >> $GITHUB_OUTPUT

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Decode kubeconfig
        env:
          KUBECONFIG_B64: ${{ secrets.KUBECONFIG }}
        run: |
          mkdir -p $HOME/.kube
          echo "$KUBECONFIG_B64" | base64 --decode > $HOME/.kube/config
          chmod 600 $HOME/.kube/config

      - name: Update image in manifest
        run: |
          IMAGE=${{ needs.build-and-push.outputs.image_full }}
          sed -i "s|PLACEHOLDER_IMAGE|${IMAGE}|g" k8s/deployment.yaml

      - name: Apply manifests
        run: |
          kubectl apply -n ${{ env.K8S_NAMESPACE }} -f k8s/
          kubectl rollout status deployment/myapp -n ${{ env.K8S_NAMESPACE }} --timeout=120s
