name: Manual Deploy to Kubernetes

on:
  workflow_dispatch:

env:
  REGISTRY: ${{ secrets.REGISTRY }}
  IMAGE_NAME: ${{ secrets.IMAGE_NAME }}
  K8S_NAMESPACE: ${{ secrets.K8S_NAMESPACE || 'default' }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: 'latest'

      - name: Configure KUBECONFIG
        run: |
          echo "${{ secrets.KUBECONFIG_DATA }}" > kubeconfig.yaml
          export KUBECONFIG=kubeconfig.yaml
          kubectl config view

      - name: Deploy to Kubernetes
        run: |
          IMAGE_TAG=${{ github.sha }}
          echo "Deploying image: $REGISTRY/$IMAGE_NAME:$IMAGE_TAG"
          kubectl -n $K8S_NAMESPACE set image deployment/myapp myapp=$REGISTRY/$IMAGE_NAME:$IMAGE_TAG
          kubectl -n $K8S_NAMESPACE rollout status deployment/myapp
